export type LanguageCode = "en" | "fr";

const accents: Record<string, string> = {
  à: "a", â: "a", ä: "a", æ: "ae", ç: "c",
  é: "e", è: "e", ê: "e", ë: "e",
  î: "i", ï: "i", ô: "o", ö: "o",
  ù: "u", û: "u", ü: "u", ÿ: "y", œ: "oe",
};

export function normalizeSearchText(value: string) {
  return String(value || "")
    .toLowerCase()
    .replace(/[àâäæçéèêëîïôöùûüÿœ]/g, (char) => accents[char] || char)
    .replace(/[’']/g, " ")
    .replace(/[^a-z0-9\s./-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export const manualSearchSynonyms: Array<[string, string[]]> = [
  ["medical bags", ["medical bags", "trauma bags", "oxygen bags", "medical backpacks", "ems bags"]],
  ["medical bag", ["medical bag", "medical bags", "trauma bag", "oxygen bag", "medical backpack", "ems bag"]],
  ["medic bags", ["medical bags", "trauma bags", "oxygen bags", "ems bags"]],
  ["medic bag", ["medical bag", "trauma bag", "oxygen bag", "ems bag"]],
  ["patient monitors", ["patient monitors", "vital signs monitors", "bedside monitors", "multi-parameter monitors"]],
  ["patient monitor", ["patient monitor", "vital signs monitor", "bedside monitor", "multi-parameter monitor"]],
  ["masks", ["masks", "face masks", "n95 masks", "n95 respirators", "respirators", "oxygen masks", "procedure face masks"]],
  ["mask", ["mask", "masks", "face mask", "n95 mask", "respirator", "oxygen mask"]],
  ["gants", ["gloves", "medical gloves", "exam gloves", "nitrile gloves", "surgical gloves"]],
  ["gant", ["glove", "gloves"]],
  ["masques rcr", ["cpr pocket masks", "pocket masks", "cpr masks", "face shields"]],
  ["masque rcr", ["cpr pocket mask", "pocket mask", "cpr mask", "face shield"]],
  ["masques", ["masks", "face masks", "n95 masks", "n95 respirators", "oxygen masks", "procedure face masks"]],
  ["masque", ["mask", "masks", "face mask", "n95 mask", "oxygen mask"]],
  ["masques n95", ["N95 masks", "N95 respirators", "N95"]],
  ["masque n95", ["N95 mask", "N95 respirator", "N95"]],
  ["n95 masks", ["N95 masks", "N95 respirators", "N95"]],
  ["n95 mask", ["N95 mask", "N95 respirator", "N95"]],
  ["respirateur", ["respirator", "mask", "n95"]],
  ["respirateurs", ["respirators", "masks", "n95"]],
  ["pansement", ["dressing", "wound dressing", "bandage"]],
  ["pansements", ["dressings", "wound dressings", "bandages"]],
  ["bandaid", ["bandage", "adhesive bandage", "band-aid", "dressing", "wound dressing"]],
  ["bandaids", ["bandages", "adhesive bandages", "band-aids", "dressings", "wound dressings"]],
  ["band aid", ["bandage", "adhesive bandage", "band-aid", "dressing", "wound dressing"]],
  ["band aids", ["bandages", "adhesive bandages", "band-aids", "dressings", "wound dressings"]],
  ["band-aid", ["bandage", "adhesive bandage", "dressing", "wound dressing"]],
  ["band-aids", ["bandages", "adhesive bandages", "dressings", "wound dressings"]],
  ["bandage", ["bandage", "adhesive bandage", "dressing", "wound dressing", "wrap"]],
  ["bandages", ["bandages", "adhesive bandages", "dressings", "wound dressings", "wraps"]],
  ["scissors", ["scissor", "medical scissors", "bandage scissor", "bandage shears"]],
  ["ciseaux", ["scissor", "medical scissors", "bandage scissor", "bandage shears"]],
  ["ciseau", ["scissor", "medical scissors", "bandage scissor"]],
  ["ciseaux a pansements", ["scissor", "bandage scissor", "dressing scissors", "medical scissors", "bandage shears"]],
  ["ciseaux à pansements", ["scissor", "bandage scissor", "dressing scissors", "medical scissors", "bandage shears"]],
  ["ciseaux medicaux", ["medical scissors", "bandage scissors", "dressing scissors"]],
  ["ciseaux médicaux", ["medical scissors", "bandage scissors", "dressing scissors"]],
  ["ciseaux chirurgicaux", ["surgical scissors", "operating scissors", "medical scissors"]],
  ["cisaille", ["shears", "scissors"]],
  ["cisailles", ["shears", "scissors"]],
  ["pinces", ["forceps", "clamps", "tweezers"]],
  ["pince", ["forceps", "clamp", "tweezers"]],
  ["pince hemostatique", ["hemostatic forceps", "hemostat", "clamp"]],
  ["pince hémostatique", ["hemostatic forceps", "hemostat", "clamp"]],
  ["garrot", ["tourniquet", "CAT tourniquet", "combat application tourniquet"]],
  ["garrots", ["tourniquets", "CAT tourniquet", "combat application tourniquet"]],
  ["cat garrot", ["CAT tourniquet", "combat application tourniquet"]],
  ["tour", ["tourniquet", "CAT tourniquet", "combat application tourniquet"]],
  ["tourn", ["tourniquet", "CAT tourniquet", "combat application tourniquet"]],
  ["tourniq", ["tourniquet", "CAT tourniquet", "combat application tourniquet"]],
  ["tourni", ["tourniquet", "CAT tourniquet", "combat application tourniquet"]],
  ["collier cervical", ["cervical collar", "neck collar"]],
  ["collier", ["collar", "cervical collar"]],
  ["attelle", ["splint"]],
  ["attelles", ["splints"]],
  ["echarpe", ["sling"]],
  ["écharpe", ["sling"]],
  ["bandage triangulaire", ["triangular bandage", "sling"]],
  ["triangulaire", ["triangular bandage"]],
  ["pansement israélien", ["Israeli bandage", "emergency bandage", "trauma bandage"]],
  ["pansement israelien", ["Israeli bandage", "emergency bandage", "trauma bandage"]],
  ["bandage israelien", ["Israeli bandage", "emergency bandage", "trauma bandage"]],
  ["bandage israélien", ["Israeli bandage", "emergency bandage", "trauma bandage"]],
  ["seringue", ["syringe"]],
  ["seringues", ["syringes"]],
  ["syr", ["syringe", "syringes"]],
  ["aiguille", ["needle"]],
  ["aiguilles", ["needles"]],
  ["aiguille stylo", ["pen needles", "pen needle"]],
  ["aiguille pour stylo", ["pen needles", "pen needle"]],
  ["aiguilles stylo", ["pen needles", "pen needle"]],
  ["aiguilles pour stylo", ["pen needles", "pen needle"]],
  ["catheter", ["catheter"]],
  ["cathéter", ["catheter"]],
  ["catheters", ["catheters"]],
  ["cathéters", ["catheters"]],
  ["sonde", ["catheter", "tube", "probe"]],
  ["sondes", ["catheters", "tubes", "probes"]],
  ["intraveineux", ["IV", "intravenous", "IV administration", "IV catheter"]],
  ["intraveineuse", ["IV", "intravenous", "IV administration", "IV catheter"]],
  ["fournitures intraveineuses", ["IV supplies", "IV administration", "IV catheter", "IV solution"]],
  ["fournitures pour perfusion intraveineuse", ["IV supplies", "IV administration", "IV catheter", "IV solution"]],
  ["fourniture pour perfusion intraveineuse", ["IV supplies", "IV administration", "IV catheter", "IV solution"]],
  ["materiel intraveineux", ["IV supplies", "IV administration", "IV catheter", "IV solution"]],
  ["matériel intraveineux", ["IV supplies", "IV administration", "IV catheter", "IV solution"]],
  ["solution intraveineuse", ["IV solution", "IV supplies", "saline", "sodium chloride"]],
  ["iv", ["IV", "intravenous", "IV administration", "IV catheter"]],
  ["perfusion", ["IV", "intravenous", "IV set", "infusion"]],
  ["fauteuil roulant", ["wheelchairs", "wheelchair"]],
  ["fauteuils roulants", ["wheelchairs", "wheelchair"]],
  ["aide a la marche", ["walker", "walkers", "rollator", "cane", "crutches", "mobility aids"]],
  ["aide à la marche", ["walker", "walkers", "rollator", "cane", "crutches", "mobility aids"]],
  ["aides a la marche", ["walker", "walkers", "rollator", "cane", "crutches", "mobility aids"]],
  ["aides à la marche", ["walker", "walkers", "rollator", "cane", "crutches", "mobility aids"]],
  ["aide a la mobilite", ["mobility aids", "walker", "walkers", "rollator", "cane", "crutches", "wheelchair"]],
  ["aide à la mobilité", ["mobility aids", "walker", "walkers", "rollator", "cane", "crutches", "wheelchair"]],
  ["aides a la mobilite", ["mobility aids", "walker", "walkers", "rollator", "cane", "crutches", "wheelchair"]],
  ["aides à la mobilité", ["mobility aids", "walker", "walkers", "rollator", "cane", "crutches", "wheelchair"]],
  ["oxygene", ["oxygen"]],
  ["oxygène", ["oxygen"]],
  ["masque oxygene", ["oxygen mask"]],
  ["masque à oxygène", ["oxygen mask"]],
  ["masque d oxygene", ["oxygen mask"]],
  ["masque d’oxygène", ["oxygen mask"]],
  ["masque avec sac", ["non-rebreather mask", "oxygen mask", "bag valve mask"]],
  ["masque avec reservoir", ["non-rebreather mask", "oxygen mask"]],
  ["masque avec réservoir", ["non-rebreather mask", "oxygen mask"]],
  ["oxygen masks", ["oxygen masks", "oxygen mask", "non-rebreather mask"]],
  ["tensiometre", ["blood pressure", "sphygmomanometer", "bp cuff"]],
  ["tensiomètre", ["blood pressure", "sphygmomanometer", "bp cuff"]],
  ["brassard", ["cuff", "blood pressure cuff"]],
  ["brassard de tension", ["blood pressure cuff"]],
  ["pression arterielle", ["blood pressure", "blood pressure monitor", "blood pressure cuff"]],
  ["pression artérielle", ["blood pressure", "blood pressure monitor", "blood pressure cuff"]],
  ["stethoscope", ["stethoscope"]],
  ["stéthoscope", ["stethoscope"]],
  ["otoscope", ["otoscope"]],
  ["otoscopes", ["otoscopes"]],
  ["ophtalmoscope", ["ophthalmoscope"]],
  ["ophtalmoscopes", ["ophthalmoscopes"]],
  ["oxymetre", ["pulse oximeter", "oximeter"]],
  ["oxymètre", ["pulse oximeter", "oximeter"]],
  ["oxymetre de pouls", ["pulse oximeter", "oximeter"]],
  ["oxymètre de pouls", ["pulse oximeter", "oximeter"]],
  ["dea", ["AED", "defibrillator", "automated external defibrillator"]],
  ["defibrillateur", ["AED", "defibrillator", "automated external defibrillator"]],
  ["défibrillateur", ["AED", "defibrillator", "automated external defibrillator"]],
  ["rcr", ["cpr"]],
  ["aed", ["AED", "defibrillator", "automated external defibrillator"]],
  ["aed defibrillator", ["AED", "defibrillator", "automated external defibrillator"]],
  ["aed defibrillation", ["AED", "defibrillator", "automated external defibrillator"]],
  ["defibrillation", ["AED", "defibrillator", "automated external defibrillator"]],
  ["defibrillator", ["AED", "automated external defibrillator"]],
  ["defibrillators", ["AED", "defibrillator", "automated external defibrillator"]],
  ["dea automatique", ["AED", "defibrillator", "automated external defibrillator"]],
  ["mannequin rcr", ["cpr manikin", "training manikin"]],
  ["mannequin", ["manikin", "training manikin", "simulation manikin", "patient simulator"]],
  ["mannequins", ["manikins", "training manikins", "simulation manikins", "patient simulators"]],
  ["mannequin de formation", ["training manikin", "simulation manikin"]],
  ["mannequin cpr", ["cpr manikin", "cpr training manikin"]],
  ["mannequin de cpr", ["cpr manikin", "cpr training manikin"]],
  ["mannequin de rcr", ["cpr manikin", "cpr training manikin"]],
  ["premiers soins", ["first aid"]],
  ["trousse premiers soins", ["first aid kit"]],
  ["trousse de premiers soins", ["first aid kit"]],
  ["trousses de premiers soins", ["first aid kits", "first aid kit"]],
  ["trousse de premiers secours", ["first aid kit", "first aid kits"]],
  ["trousses de premiers secours", ["first aid kits", "first aid kit"]],
  ["trousse premiers secours", ["first aid kit", "first aid kits"]],
  ["trousses premiers secours", ["first aid kits", "first aid kit"]],
  ["trousse premiers", ["first aid kit"]],
  ["ifak", ["IFAK", "individual first aid kit", "trauma kit"]],
  ["chaise douche", ["shower chair"]],
  ["chaise de douche", ["shower chair"]],
  ["fauteuil de douche", ["shower chair"]],
  ["siege de douche", ["shower chair"]],
  ["siège de douche", ["shower chair"]],
  ["banc de transfert", ["transfer bench"]],
  ["banc de bain", ["bath bench", "shower bench"]],
  ["banc douche", ["shower bench", "bath bench"]],
  ["siege bain", ["bath seat", "shower chair"]],
  ["siège bain", ["bath seat", "shower chair"]],
  ["commode", ["commode", "toilet chair"]],
  ["chaise d aisance", ["commode", "toilet chair"]],
  ["chaise d’aisance", ["commode", "toilet chair"]],
  ["canne", ["cane"]],
  ["cannes", ["canes"]],
  ["bequille", ["crutch"]],
  ["béquille", ["crutch"]],
  ["bequilles", ["crutches"]],
  ["béquilles", ["crutches"]],
  ["deambulateur", ["walker", "walkers", "rollator"]],
  ["déambulateur", ["walker", "walkers", "rollator"]],
  ["marchette", ["walker", "walkers", "rollator"]],
  ["marchettes", ["walker", "walkers", "rollator"]],
  ["marcheur", ["walker", "walkers", "rollator"]],
  ["marcheurs", ["walker", "walkers", "rollator"]],
  ["marcheuse", ["walker", "walkers", "rollator"]],
  ["marcheuses", ["walker", "walkers", "rollator"]],
  ["rollator", ["rollator", "walker"]],
  ["ambulateur", ["walker", "walkers", "rollator"]],
  ["glucometre", ["glucose meter", "glucometer"]],
  ["glucomètre", ["glucose meter", "glucometer"]],
  ["glycemie", ["blood glucose", "glucose meter", "test strips"]],
  ["glycémie", ["blood glucose", "glucose meter", "test strips"]],
  ["bandelettes", ["test strips", "glucose test strips"]],
  ["bandelette", ["test strip", "glucose test strip"]],
  ["bandelettes test", ["test strips", "glucose test strips"]],
  ["bandelettes de test contour next", ["Contour Next test strips", "Contour Next strips"]],
  ["bandelette de test contour next", ["Contour Next test strips", "Contour Next strips"]],
  ["contour next", ["contour next", "test strips", "glucose test strips"]],
  ["accu chek", ["accu-chek", "glucose test strips", "glucometer"]],
  ["thermometre", ["thermometer"]],
  ["thermomètre", ["thermometer"]],
  ["compresses", ["gauze", "sponges"]],
  ["compresse", ["gauze", "sponge"]],
  ["gaze", ["gauze"]],
  ["gaze sterile", ["sterile gauze", "gauze"]],
  ["compresses steriles", ["sterile gauze", "sterile sponges"]],
  ["compresses stériles", ["sterile gauze", "sterile sponges"]],
  ["soin des plaies", ["wound care", "wound dressing", "dressings", "gauze", "bandages"]],
  ["soins des plaies", ["wound care", "wound dressing", "dressings", "gauze", "bandages"]],
  ["soins de plaies", ["wound care", "wound dressing", "dressings", "gauze", "bandages"]],
  ["traitement des plaies", ["wound care", "wound dressing", "dressings", "gauze", "bandages"]],
  ["plaie", ["wound", "wound care", "wound dressing"]],
  ["plaies", ["wounds", "wound care", "wound dressings"]],
  ["rouleau de gaze", ["gauze roll"]],
  ["rouleaux de gaze", ["gauze rolls"]],
  ["ruban medical", ["medical tape"]],
  ["ruban médical", ["medical tape"]],
  ["ruban adhesif", ["medical tape", "adhesive tape"]],
  ["ruban adhésif", ["medical tape", "adhesive tape"]],
  ["steri strip", ["steri-strip", "wound closure strips"]],
  ["diachylon", ["medical tape", "adhesive tape"]],
  ["sparadrap", ["medical tape", "adhesive tape"]],
  ["lit medical", ["medical bed", "hospital bed"]],
  ["lit médical", ["medical bed", "hospital bed"]],
  ["alese", ["underpad", "bed pad"]],
  ["alèse", ["underpad", "bed pad"]],
  ["aleses", ["underpads", "bed pads"]],
  ["alèses", ["underpads", "bed pads"]],
  ["protection", ["underpad", "protective pad"]],
  ["incontinence", ["incontinence", "briefs", "underpads"]],
  ["couche adulte", ["adult brief", "incontinence brief"]],
  ["blouse", ["gown", "medical gown"]],
  ["blouses", ["gowns", "medical gowns"]],
  ["sarrau", ["lab coat", "coat"]],
  ["sarraus", ["lab coats", "coats"]],
  ["bassin", ["basin", "bedpan"]],
  ["urinal", ["urinal"]],
  ["sac vomitoire", ["emesis bag", "vomit bag"]],
  ["sacs vomitoires", ["emesis bags", "vomit bags"]],
  ["sac biohazard", ["biohazard bag"]],
  ["dechet biomedical", ["biohazard waste", "medical waste"]],
  ["déchet biomédical", ["biohazard waste", "medical waste"]],
  ["contenant objets tranchants", ["sharps container"]],
  ["contenant tranchants", ["sharps container"]],
  ["boite aiguilles", ["sharps container"]],
  ["boîte aiguilles", ["sharps container"]],
  ["sac ambu", ["bag valve mask", "bvm", "resuscitator"]],
  ["ballon masque", ["bag valve mask", "bvm", "resuscitator"]],
  ["ballon autoremplisseur", ["bag valve mask", "bvm", "resuscitator"]],
  ["masque de poche", ["pocket mask", "CPR pocket mask"]],
  ["bvm de poche", ["pocket BVM", "bag valve mask", "BVM"]],
  ["aspiration", ["suction", "suction catheter", "suction unit"]],
  ["succion", ["suction", "suction catheter", "suction unit"]],
  ["voie aerienne", ["airway", "airway management"]],
  ["voie aérienne", ["airway", "airway management"]],
  ["canule nasale", ["nasal cannula"]],
  ["nasal", ["nasal", "nasal cannula"]],
  ["epipen", ["epipen", "epinephrine auto injector"]],
  ["epi pen", ["epipen", "epinephrine auto injector"]],
  ["epinephrine", ["epinephrine", "epipen"]],
  ["épinéphrine", ["epinephrine", "epipen"]],
  ["saline", ["saline", "sodium chloride", "NaCl"]],
  ["solution saline", ["saline", "sodium chloride", "NaCl"]],
  ["serum physiologique", ["saline", "sodium chloride", "NaCl"]],
  ["sérum physiologique", ["saline", "sodium chloride", "NaCl"]],
  ["nacl", ["NaCl", "saline", "sodium chloride"]],
  ["eau sterile", ["sterile water"]],
  ["eau stérile", ["sterile water"]],
  ["alcool", ["alcohol", "alcohol swabs", "prep pads"]],
  ["tampon alcool", ["alcohol swabs", "prep pads"]],
  ["tampons alcool", ["alcohol swabs", "prep pads"]],
  ["lingette alcool", ["alcohol swabs", "prep pads"]],
  ["lingettes alcool", ["alcohol swabs", "prep pads"]],
  ["hemostat", ["hemostat", "hemostatic forceps"]],
  ["hemostatique", ["hemostat", "hemostatic dressing", "hemostatic forceps"]],
  ["hémostatique", ["hemostat", "hemostatic dressing", "hemostatic forceps"]],
  ["chest seal", ["chest seal", "occlusive dressing"]],
  ["pansement thoracique", ["chest seal", "occlusive dressing"]],
  ["olaes", ["OLAES", "emergency bandage", "trauma bandage"]],
  ["attelle sam", ["SAM splint", "splint"]],
  ["sam splint", ["SAM splint", "splint"]],
  ["brulure", ["burn dressing", "burn care"]],
  ["brûlure", ["burn dressing", "burn care"]],
  ["pansement brulure", ["burn dressing", "burn care"]],
  ["pansement brûlure", ["burn dressing", "burn care"]],
  ["couverture", ["blanket", "emergency blanket"]],
  ["oreiller", ["pillow"]],
  ["civiere", ["stretcher", "scoop stretcher"]],
  ["civière", ["stretcher", "scoop stretcher"]],
  ["brancard", ["stretcher", "transport stretcher", "ambulance stretcher"]],
  ["brancards", ["stretchers", "stretcher", "transport stretcher", "ambulance stretcher"]],
  ["scoop", ["scoop stretcher", "stretcher"]],
  ["sac vomi", ["emesis bag", "vomit bag"]],
  ["vomit", ["emesis bag", "vomit bag"]],
  ["sac", ["bag", "medical bag", "trauma bag"]],
  ["sacs", ["bags", "medical bags", "trauma bags"]],
  ["sac medical", ["medical bag", "trauma bag"]],
  ["sac médical", ["medical bag", "trauma bag"]],
  ["sacs medicaux", ["medical bags", "trauma bags", "ems bags"]],
  ["sacs médicaux", ["medical bags", "trauma bags", "ems bags"]],
  ["sac trauma", ["trauma bag", "medical bag"]],
  ["sharps", ["sharps container"]],
  ["sharp", ["sharps container"]],
  ["tranchants", ["sharps container"]],
  ["objets tranchants", ["sharps container"]],
  ["lavage oculaire", ["eye wash", "eyewash"]],
  ["rince oeil", ["eye wash", "eyewash"]],
  ["rince œil", ["eye wash", "eyewash"]],
  ["oeil", ["eye", "eye wash", "eye care"]],
  ["œil", ["eye", "eye wash", "eye care"]],
  ["bp cuff", ["blood pressure cuff", "sphygmomanometer"]],
  ["blood pressure", ["sphygmomanometer", "bp cuff"]],
  ["defib", ["defibrillator"]],
  ["defib pads", ["aed pads", "defibrillator pads"]],
  ["non rebreather", ["oxygen mask", "non-rebreather mask"]],
  ["ambu bag", ["bag valve mask", "bvm", "resuscitator"]],
  ["bvm", ["bag valve mask", "resuscitator"]],
  ["foley", ["foley catheter", "urinary catheter", "catheter"]],
  ["sonde foley", ["foley catheter", "urinary catheter"]],
  ["zoll", ["Zoll"]],
  ["glucose", ["glucose", "blood glucose", "glucose meter", "test strips"]],
  ["dextrose", ["dextrose", "glucose"]],
  ["dex", ["Dex4", "dextrose", "glucose tablets"]],
  ["dex4", ["Dex4", "dextrose", "glucose tablets"]],
  ["sodium chloride", ["sodium chloride", "NaCl", "saline"]],
  ["bacteriostatic", ["bacteriostatic water", "bacteriostatic sodium chloride"]],
  ["bacteriostatique", ["bacteriostatic water", "bacteriostatic sodium chloride"]],
  ["bac water", ["bacteriostatic water"]],
  ["eau bacteriostatique", ["bacteriostatic water"]],
  ["eau bactériostatique", ["bacteriostatic water"]],
  ["hyfin", ["HyFin", "chest seal", "occlusive dressing"]],
  ["quikclot", ["QuikClot", "hemostatic dressing", "hemostatic gauze"]],
  ["quick clot", ["QuikClot", "hemostatic dressing", "hemostatic gauze"]],
  ["combat gauze", ["Combat Gauze", "hemostatic gauze", "hemostatic dressing"]],
  ["pansement hemostatique", ["hemostatic dressing", "hemostatic gauze", "QuikClot"]],
  ["pansement hémostatique", ["hemostatic dressing", "hemostatic gauze", "QuikClot"]],
  ["compresse froide", ["cold pack", "ice pack"]],
  ["bloc froid", ["cold pack", "ice pack"]],
  ["ice pack", ["ice pack", "cold pack"]],
  ["cold pack", ["cold pack", "ice pack"]],
  ["cold packs", ["cold packs", "ice packs"]],
  ["sked", ["Sked", "stretcher", "rescue stretcher"]],
  ["emises bags", ["emesis bags", "vomit bags"]],
  ["emesis", ["emesis bag", "vomit bag"]],
  ["tube endotracheal", ["endotracheal tube", "ET tube"]],
  ["tube endotrachéal", ["endotracheal tube", "ET tube"]],
  ["endotracheal tube", ["endotracheal tube", "ET tube"]],
  ["laryngoscope", ["laryngoscope"]],
  ["nebulizer", ["nebulizer", "nebulizer mask"]],
  ["nebuliseur", ["nebulizer", "nebulizer mask"]],
  ["nébuliseur", ["nebulizer", "nebulizer mask"]],
  ["hospira", ["Hospira", "sterile water", "sodium chloride"]],
  ["27g", ["27g needle", "27 gauge needle"]],
  ["regulator", ["oxygen regulator", "regulator"]],
  ["regulateur", ["oxygen regulator", "regulator"]],
  ["régulateur", ["oxygen regulator", "regulator"]],
  ["biopsi pouch", ["biopsy pouch", "specimen bag"]],
  ["biopsie poncho", ["biopsy punch", "biopsy punches"]],
  ["biopsy punches", ["biopsy punch", "biopsy punches"]],
  ["poinçon biopsie", ["biopsy punch", "biopsy punches"]],
  ["poincon biopsie", ["biopsy punch", "biopsy punches"]],
  ["speculum", ["speculum"]],
  ["spéculum", ["speculum"]],
  ["thermometer", ["thermometer"]],
  ["edan", ["EDAN"]],
  ["statpack", ["StatPacks", "medical bag", "trauma bag"]],
  ["statpacks", ["StatPacks", "medical bag", "trauma bag"]],
  ["g3", ["G3", "StatPacks"]],
  ["practi", ["Practi", "training", "simulation"]],
  ["demo dose", ["Demo Dose", "training", "simulation"]],
  ["mad300", ["MAD300", "mucosal atomization device"]],
  ["lma", ["LMA", "laryngeal mask airway"]],
  ["ecg", ["ECG", "electrodes", "ECG paper"]],
  ["vacutainer", ["Vacutainer", "blood collection"]],
  ["bodi white", ["body white", "body"]],
  ["bodi wheel", ["body wheel", "wheelchair"]],
  ["bear wheel", ["wheelchair"]],
  ["engin bag", ["engine bag", "medical bag", "trauma bag"]],
  ["emin bag", ["medical bag", "trauma bag"]],
  ["eleg bag", ["medical bag", "trauma bag"]],
];

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function matchesNormalizedTerm(normalizedQuery: string, normalizedTerm: string) {
  if (!normalizedQuery || !normalizedTerm) return false;
  if (normalizedQuery === normalizedTerm) return true;
  const pattern = new RegExp(`(^|\\s)${escapeRegExp(normalizedTerm)}(?=\\s|$)`);
  return pattern.test(normalizedQuery);
}

const frenchSignals = [
  "gants", "gant", "masques", "masque", "pansement", "seringue", "aiguille",
  "ciseaux", "ciseau", "cisaille", "garrot", "pince", "pinces", "collier", "attelle",
  "fauteuil", "oxygene", "oxygène", "tensiometre", "tensiomètre", "brassard",
  "defibrillateur", "défibrillateur", "premiers", "trousse", "deambulateur",
  "déambulateur", "marchette", "marchettes", "marcheuse", "marcheuses", "marcheur", "marcheurs",
  "aide", "aides", "marche", "mobilite", "mobilité",
  "thermometre", "thermomètre", "ruban", "mannequin", "chaise",
  "banc", "canne", "lit", "compresse", "compresses", "cathéter", "catheter",
  "oxymetre", "oxymètre", "bandelette", "bandelettes", "sparadrap", "alèse", "alese",
  "plaie", "plaies", "soin", "soins", "bacteriostatique", "bactériostatique",
  "hemostatique", "hémostatique", "endotracheal", "endotrachéal", "nebuliseur",
  "nébuliseur", "regulateur", "régulateur", "biopsie", "spéculum", "compresse froide",
  "bloc froid", "poinçon", "poincon", "civière", "civiere", "brancard", "brancards"
];

export function detectQueryLanguage(query: string): LanguageCode {
  const normalized = normalizeSearchText(query);
  if (/[àâäçéèêëîïôöùûüÿœ]/i.test(query)) return "fr";
  if (frenchSignals.some((term) => normalized.includes(normalizeSearchText(term)))) return "fr";
  return "en";
}

export function expandSearchQuery(query: string) {
  const normalized = normalizeSearchText(query);
  const additions = new Set<string>();
  const matchedTerms: string[] = [];

  const orderedSynonyms = [...manualSearchSynonyms].sort((a, b) =>
    normalizeSearchText(b[0]).length - normalizeSearchText(a[0]).length
  );

  for (const [term, synonyms] of orderedSynonyms) {
    const normalizedTerm = normalizeSearchText(term);
    if (matchedTerms.some((matchedTerm) => matchedTerm !== normalizedTerm && matchedTerm.includes(normalizedTerm))) {
      continue;
    }
    if (matchesNormalizedTerm(normalized, normalizedTerm)) {
      matchedTerms.push(normalizedTerm);
      synonyms.forEach((synonym) => additions.add(synonym));
    }
  }

  return {
    original: query,
    expanded: [query, ...Array.from(additions)].join(" "),
    language: detectQueryLanguage(query),
    expansions: Array.from(additions),
  };
}

export function getFallbackTerms(query: string) {
  const normalized = normalizeSearchText(query);
  const suggestions = new Set<string>();

  for (const [term, synonyms] of manualSearchSynonyms) {
    const normalizedTerm = normalizeSearchText(term);
    if (matchesNormalizedTerm(normalized, normalizedTerm) || matchesNormalizedTerm(normalizedTerm, normalized)) {
      synonyms.slice(0, 4).forEach((synonym) => suggestions.add(synonym));
    }
  }

  if (!suggestions.size) {
    ["gloves", "masks", "first aid", "oxygen", "wound dressing", "syringe"].forEach((term) => suggestions.add(term));
  }

  return Array.from(suggestions).slice(0, 6);
}
